#!/bin/bash

# One-Place-Chat Backup Cron Setup Script
# This script sets up automated backup schedules using cron

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$(dirname "$SCRIPT_DIR")")"
SCHEDULED_BACKUP_SCRIPT="$SCRIPT_DIR/scheduled-backup.sh"
BACKUP_CONFIG="$PROJECT_ROOT/devops/backup/backup-config.yml"

# Function to log messages
log() {
    echo -e "${BLUE}[$(date +'%Y-%m-%d %H:%M:%S')]${NC} $1"
}

error() {
    echo -e "${RED}[ERROR]${NC} $1" >&2
}

success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

# Function to check if running as root
check_root() {
    if [ "$EUID" -ne 0 ]; then
        error "This script must be run as root to setup cron jobs"
        exit 1
    fi
}

# Function to check prerequisites
check_prerequisites() {
    log "Checking prerequisites..."
    
    # Check if scheduled backup script exists
    if [ ! -f "$SCHEDULED_BACKUP_SCRIPT" ]; then
        error "Scheduled backup script not found: $SCHEDULED_BACKUP_SCRIPT"
        exit 1
    fi
    
    # Check if backup config exists
    if [ ! -f "$BACKUP_CONFIG" ]; then
        warning "Backup config not found: $BACKUP_CONFIG"
        warning "Using default backup configuration"
    fi
    
    # Check if cron is installed
    if ! command -v crontab >/dev/null 2>&1; then
        error "cron is not installed"
        exit 1
    fi
    
    success "Prerequisites check passed"
}

# Function to create backup user
create_backup_user() {
    log "Creating backup user..."
    
    if ! id "backup" >/dev/null 2>&1; then
        useradd -r -s /bin/bash -d /opt/backups backup
        success "Backup user created"
    else
        log "Backup user already exists"
    fi
    
    # Create backup directories
    mkdir -p /opt/backups/one-place-chat
    mkdir -p /var/log
    chown -R backup:backup /opt/backups
    chown -R backup:backup /var/log
    
    success "Backup directories created"
}

# Function to setup environment for backup user
setup_backup_environment() {
    log "Setting up backup user environment..."
    
    # Create backup user's bash profile
    cat > /home/backup/.bashrc << 'EOF'
# One-Place-Chat Backup Environment
export PATH="/usr/local/bin:/usr/bin:/bin"
export ENVIRONMENT=production
export BACKUP_TYPE=full
export RETENTION_DAYS=7

# Docker environment
export DOCKER_HOST=unix:///var/run/docker.sock

# Project paths
export PROJECT_ROOT="/home/elbadry_/Desktop/One-Place-Chat"
export BACKUP_SCRIPT_DIR="$PROJECT_ROOT/devops/scripts"

# Logging
export LOG_FILE="/var/log/opc-backup.log"
EOF
    
    # Copy environment file if it exists
    if [ -f "$PROJECT_ROOT/.env" ]; then
        cp "$PROJECT_ROOT/.env" /home/backup/.env
        chown backup:backup /home/backup/.env
        chmod 600 /home/backup/.env
    fi
    
    success "Backup user environment setup completed"
}

# Function to create cron jobs
create_cron_jobs() {
    log "Creating cron jobs..."
    
    # Backup user's crontab
    cat > /tmp/backup_crontab << 'EOF'
# One-Place-Chat Backup Schedule
# Generated by setup-backup-cron.sh

# Full backup - daily at 2 AM
0 2 * * * /home/elbadry_/Desktop/One-Place-Chat/devops/scripts/scheduled-backup.sh full 7 >> /var/log/opc-backup.log 2>&1

# ChromaDB backup - every 6 hours
0 */6 * * * /home/elbadry_/Desktop/One-Place-Chat/devops/scripts/scheduled-backup.sh chromadb 3 >> /var/log/opc-backup.log 2>&1

# Application data backup - daily at 3 AM
0 3 * * * /home/elbadry_/Desktop/One-Place-Chat/devops/scripts/scheduled-backup.sh application 14 >> /var/log/opc-backup.log 2>&1

# Docker volumes backup - weekly on Sunday at 1 AM
0 1 * * 0 /home/elbadry_/Desktop/One-Place-Chat/devops/scripts/scheduled-backup.sh volumes 30 >> /var/log/opc-backup.log 2>&1

# Log rotation - daily at midnight
0 0 * * * /usr/sbin/logrotate /etc/logrotate.d/opc-backup
EOF
    
    # Install crontab for backup user
    crontab -u backup /tmp/backup_crontab
    rm /tmp/backup_crontab
    
    success "Cron jobs created"
}

# Function to create logrotate configuration
create_logrotate_config() {
    log "Creating logrotate configuration..."
    
    cat > /etc/logrotate.d/opc-backup << 'EOF'
/var/log/opc-backup.log {
    daily
    missingok
    rotate 30
    compress
    delaycompress
    notifempty
    create 644 backup backup
    postrotate
        # Reload any services that might be using the log file
    endscript
}
EOF
    
    success "Logrotate configuration created"
}

# Function to create systemd service (alternative to cron)
create_systemd_service() {
    log "Creating systemd service..."
    
    cat > /etc/systemd/system/opc-backup.service << EOF
[Unit]
Description=One-Place-Chat Backup Service
After=docker.service
Requires=docker.service

[Service]
Type=oneshot
User=backup
Group=backup
WorkingDirectory=$PROJECT_ROOT
Environment=ENVIRONMENT=production
Environment=BACKUP_TYPE=full
Environment=RETENTION_DAYS=7
ExecStart=$SCHEDULED_BACKUP_SCRIPT
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

    cat > /etc/systemd/system/opc-backup.timer << EOF
[Unit]
Description=One-Place-Chat Backup Timer
Requires=opc-backup.service

[Timer]
OnCalendar=daily
Persistent=true

[Install]
WantedBy=timers.target
EOF
    
    # Reload systemd and enable timer
    systemctl daemon-reload
    systemctl enable opc-backup.timer
    
    success "Systemd service created"
}

# Function to setup monitoring
setup_monitoring() {
    log "Setting up backup monitoring..."
    
    # Create backup monitoring script
    cat > /opt/backups/monitor-backups.sh << 'EOF'
#!/bin/bash

# Backup monitoring script
LOG_FILE="/var/log/opc-backup.log"
ALERT_THRESHOLD_HOURS=25  # Alert if no backup in 25 hours

LAST_BACKUP=$(grep "Scheduled backup completed successfully" "$LOG_FILE" | tail -1 | cut -d' ' -f1-2)
if [ -z "$LAST_BACKUP" ]; then
    echo "No successful backup found in logs"
    exit 1
fi

LAST_BACKUP_TIMESTAMP=$(date -d "$LAST_BACKUP" +%s)
CURRENT_TIMESTAMP=$(date +%s)
HOURS_SINCE_BACKUP=$(( (CURRENT_TIMESTAMP - LAST_BACKUP_TIMESTAMP) / 3600 ))

if [ $HOURS_SINCE_BACKUP -gt $ALERT_THRESHOLD_HOURS ]; then
    echo "ALERT: No backup in $HOURS_SINCE_BACKUP hours"
    # Send alert notification here
    exit 1
fi

echo "Backup is up to date (last backup: $HOURS_SINCE_BACKUP hours ago)"
EOF
    
    chmod +x /opt/backups/monitor-backups.sh
    
    # Add monitoring to crontab
    echo "# Backup monitoring - every hour" >> /tmp/backup_crontab
    echo "0 * * * * /opt/backups/monitor-backups.sh >> /var/log/opc-backup-monitor.log 2>&1" >> /tmp/backup_crontab
    
    crontab -u backup /tmp/backup_crontab
    rm /tmp/backup_crontab
    
    success "Backup monitoring setup completed"
}

# Function to test backup
test_backup() {
    log "Testing backup system..."
    
    # Run a test backup
    if sudo -u backup "$SCHEDULED_BACKUP_SCRIPT" "application" "1"; then
        success "Test backup completed successfully"
    else
        error "Test backup failed"
        exit 1
    fi
}

# Function to display status
display_status() {
    log "Backup system status:"
    echo ""
    echo "Cron jobs:"
    crontab -u backup -l
    echo ""
    echo "Systemd timers:"
    systemctl list-timers opc-backup.timer --no-pager
    echo ""
    echo "Backup directory:"
    ls -la /opt/backups/one-place-chat/
    echo ""
    echo "Log files:"
    ls -la /var/log/opc-backup*
    echo ""
    echo "Useful commands:"
    echo "  View backup logs: tail -f /var/log/opc-backup.log"
    echo "  Run manual backup: sudo -u backup $SCHEDULED_BACKUP_SCRIPT"
    echo "  Check cron jobs: crontab -u backup -l"
    echo "  Check systemd timers: systemctl list-timers opc-backup.timer"
}

# Main function
main() {
    log "Setting up One-Place-Chat backup automation..."
    
    check_root
    check_prerequisites
    create_backup_user
    setup_backup_environment
    create_cron_jobs
    create_logrotate_config
    create_systemd_service
    setup_monitoring
    test_backup
    display_status
    
    success "Backup automation setup completed!"
    log "Backups will run automatically according to the schedule"
}

# Run main function
main "$@"
